{{- if (.Values.traefik).enabled -}}
{{- $applicationNameTpl := include "application.name" . -}}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $applicationNameTpl }}
  namespace: {{ include "application.namespace" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  {{- if .Values.traefik.additionalLabels }}
    {{ toYaml .Values.traefik.additionalLabels | indent 4 }}
  {{- end }}
  {{- if .Values.traefik.annotations }}
  annotations:
    {{ toYaml .Values.traefik.annotations | indent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range (default (list "web" "websecure") .Values.traefik.entryPoints) }}
      - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.traefik.routes }}
    - match: {{ .match }}
      kind: {{ .kind }}
      services:
        {{- range .services }}
        - name: {{ default $applicationNameTpl .name }}
          port: {{ .port }}
          {{- if .scheme }}
          scheme: {{ .scheme }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- if .Values.traefik.tls }}
  tls:
    secretName: {{ .Values.traefik.tls.secretName }}
  {{- end }}
{{- end }}